# Generated by Django 3.0.5 on 2020-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('contact_name', models.CharField(max_length=300)),
                ('gstin', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=160)),
                ('bank_account_number', models.IntegerField()),
                ('bank_account_name', models.CharField(max_length=300)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_branch_name', models.CharField(max_length=200)),
                ('bank_ifs_code', models.CharField(max_length=20)),
                ('entity_type', models.CharField(choices=[('manufacturer', 'MANUFACTURER'), ('buyer', 'BUYER'), ('firm', 'Firm')], default='buyer', max_length=20)),
            ],
        ),
    ]
