# Generated by Django 3.0.5 on 2020-06-19 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address_line_1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_line_2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_ifs_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='entity_type',
            field=models.CharField(choices=[('manufacturer', 'MANUFACTURER'), ('buyer', 'BUYER'), ('firm', 'FIRM')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='zipcode',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
