# Generated by Django 3.0.5 on 2020-06-20 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200620_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_account_number',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_ifs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
