# Generated by Django 3.0.5 on 2020-06-20 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measuring_unit',
            field=models.CharField(default='units', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='basic_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
