# Generated by Django 3.0.5 on 2020-06-20 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20200620_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_utgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('terms_of_payment', models.TextField(blank=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=100)),
                ('other_ref', models.CharField(blank=True, max_length=100)),
                ('buyer_order_number', models.CharField(blank=True, max_length=100)),
                ('buyer_order_date', models.DateField(blank=True)),
                ('despatch_document_number', models.CharField(blank=True, max_length=100)),
                ('delivery_note', models.TextField(blank=True)),
                ('terms_of_delivery', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_invoices', to='myapi.Vendor')),
                ('seller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_invoices', to='myapi.Vendor')),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='myapi.Session')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('hsn_sac', models.CharField(max_length=100)),
                ('gst_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('measuring_unit', models.CharField(default='units', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model_serial_number', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='myapi.Invoice')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='myapi.Product')),
            ],
        ),
    ]
