# Generated by Django 3.0.5 on 2020-06-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20200620_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
