# Generated by Django 3.0.5 on 2020-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20200620_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default='U.V. Cabinet', max_length=100),
            preserve_default=False,
        ),
    ]
